[CmdletBinding()]
param(
    [string[]]$RadioIp,
    [string]$EthernetAdapter,
    [string]$WifiAdapter,
    [ValidateRange(1, 60)]
    [int]$IntervalSeconds = 2,
    [string]$ResultsRoot = (Join-Path $env:USERPROFILE 'Desktop\Radio Test Results')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Section {
    param([string]$Message)
    Write-Host "`n=== $Message ===" -ForegroundColor Cyan
}

function Get-PhysicalAdapters {
    @(Get-NetAdapter -Physical -ErrorAction SilentlyContinue | Sort-Object Name)
}

function Select-AdapterName {
    param(
        [string]$RequestedName,
        [ValidateSet('Ethernet', 'Wi-Fi')]
        [string]$Kind
    )

    $all = Get-PhysicalAdapters
    if ($Kind -eq 'Wi-Fi') {
        $candidates = @($all | Where-Object {
            $_.Name -match 'Wi-?Fi|Wireless|WLAN' -or
            $_.InterfaceDescription -match 'Wi-?Fi|Wireless|802\.11'
        })
    } else {
        $candidates = @($all | Where-Object {
            $_.Name -notmatch 'Wi-?Fi|Wireless|WLAN' -and
            $_.InterfaceDescription -notmatch 'Wi-?Fi|Wireless|802\.11'
        })
    }

    if ($RequestedName) {
        $exact = $all | Where-Object Name -eq $RequestedName | Select-Object -First 1
        if (-not $exact) {
            throw "$Kind adapter '$RequestedName' was not found."
        }
        return $exact.Name
    }

    # Prefer an interface already configured on the radio-management subnet.
    # This prevents a disconnected USB dock NIC from winning over a dedicated
    # onboard radio NIC such as Ethernet 2.
    $suggested = $candidates | Where-Object {
        @(Get-NetIPAddress -InterfaceAlias $_.Name -AddressFamily IPv4 -ErrorAction SilentlyContinue |
            Where-Object IPAddress -like '10.1.0.*').Count -gt 0
    } | Select-Object -First 1
    if (-not $suggested) {
        $suggested = $candidates | Where-Object Name -eq 'Ethernet 2' | Select-Object -First 1
    }
    if (-not $suggested) {
        $suggested = $candidates | Where-Object Status -eq 'Up' | Select-Object -First 1
    }
    if (-not $suggested) {
        $suggested = $candidates | Select-Object -First 1
    }
    if (-not $suggested) {
        throw "No physical $Kind adapter was found."
    }

    $answer = Read-Host "$Kind adapter to watch [$($suggested.Name)]"
    if ([string]::IsNullOrWhiteSpace($answer)) {
        return $suggested.Name
    }
    $chosen = $all | Where-Object Name -eq $answer | Select-Object -First 1
    if (-not $chosen) {
        throw "$Kind adapter '$answer' was not found."
    }
    return $chosen.Name
}

function Get-AdapterSnapshot {
    param([string]$Name)

    if ([string]::IsNullOrWhiteSpace($Name)) {
        return [pscustomobject]@{ Name = 'not monitored'; Status = 'not monitored'; IPv4 = ''; LinkSpeed = '' }
    }

    $adapter = Get-NetAdapter -Name $Name -ErrorAction SilentlyContinue
    $addresses = @(
        Get-NetIPAddress -InterfaceAlias $Name -AddressFamily IPv4 -ErrorAction SilentlyContinue |
            Where-Object { $_.IPAddress -notlike '169.254.*' } |
            Select-Object -ExpandProperty IPAddress
    )
    [pscustomobject]@{
        Name = $Name
        Status = if ($adapter) { [string]$adapter.Status } else { 'Missing' }
        IPv4 = $addresses -join ';'
        LinkSpeed = if ($adapter) { [string]$adapter.LinkSpeed } else { '' }
    }
}

function Get-PreferredDefaultRoute {
    $routes = @(Get-NetRoute -AddressFamily IPv4 -DestinationPrefix '0.0.0.0/0' -ErrorAction SilentlyContinue)
    $ranked = foreach ($route in $routes) {
        $ipInterface = Get-NetIPInterface -AddressFamily IPv4 -InterfaceIndex $route.InterfaceIndex -ErrorAction SilentlyContinue
        $interfaceMetric = if ($ipInterface) { [int]$ipInterface.InterfaceMetric } else { 99999 }
        [pscustomobject]@{
            InterfaceIndex = $route.InterfaceIndex
            InterfaceAlias = $route.InterfaceAlias
            NextHop = $route.NextHop
            TotalMetric = [int]$route.RouteMetric + $interfaceMetric
        }
    }
    $ranked | Sort-Object TotalMetric | Select-Object -First 1
}

function Test-RadioPing {
    param([string]$Address)
    $reply = (& ping.exe -n 1 -w 700 $Address 2>&1 | Out-String)
    # Windows may return exit code 0 for an ICMP "destination unreachable"
    # generated by another interface. A TTL is present only in a real echo reply.
    return ($reply -match '(?i)TTL[= ]\d+')
}

function Get-ArpMac {
    param([string]$Address)
    $neighbor = Get-NetNeighbor -AddressFamily IPv4 -IPAddress $Address -ErrorAction SilentlyContinue |
        Where-Object { $_.State -notin @('Unreachable', 'Incomplete') } |
        Select-Object -First 1
    if ($neighbor) { return [string]$neighbor.LinkLayerAddress }
    return ''
}

function Invoke-LocalApi {
    param([string]$Uri)
    try {
        [pscustomobject]@{
            Reachable = $true
            Data = Invoke-RestMethod -Uri $Uri -TimeoutSec 2
            Error = ''
        }
    } catch {
        [pscustomobject]@{
            Reachable = $false
            Data = $null
            Error = $_.Exception.Message
        }
    }
}

function Get-Observation {
    param(
        [string]$Address,
        [string]$EthernetName,
        [string]$WifiName
    )

    $ethernet = Get-AdapterSnapshot -Name $EthernetName
    $wifi = Get-AdapterSnapshot -Name $WifiName
    $route = Get-PreferredDefaultRoute
    $ping = Test-RadioPing -Address $Address
    $mac = Get-ArpMac -Address $Address
    $chud = Invoke-LocalApi -Uri 'http://127.0.0.1:8443/api/radio/devices'
    $arc = Invoke-LocalApi -Uri 'http://127.0.0.1:9101/api/radio/mesh'

    $chudCount = if ($chud.Reachable) { @($chud.Data.devices).Count } else { -1 }
    $arcObserved = if ($arc.Reachable) { [int]$arc.Data.observed_node_count } else { -1 }
    $arcConnected = if ($arc.Reachable) { [int]$arc.Data.connected_node_count } else { -1 }
    $arcLinks = if ($arc.Reachable) { [int]$arc.Data.connected_link_count } else { -1 }

    [pscustomobject]@{
        Timestamp = (Get-Date).ToString('o')
        RadioIp = $Address
        RadioPing = $ping
        ArpMac = $mac
        EthernetAdapter = $ethernet.Name
        EthernetStatus = $ethernet.Status
        EthernetIPv4 = $ethernet.IPv4
        EthernetLinkSpeed = $ethernet.LinkSpeed
        WifiAdapter = $wifi.Name
        WifiStatus = $wifi.Status
        WifiIPv4 = $wifi.IPv4
        DefaultRouteInterface = if ($route) { $route.InterfaceAlias } else { '' }
        DefaultRouteNextHop = if ($route) { $route.NextHop } else { '' }
        ChudReachable = $chud.Reachable
        ChudDeviceCount = $chudCount
        ArcReachable = $arc.Reachable
        ArcObservedNodes = $arcObserved
        ArcConnectedNodes = $arcConnected
        ArcMeshLinks = $arcLinks
    }
}

function Write-Observation {
    param([pscustomobject]$Observation)

    $radioColor = if ($Observation.RadioPing) { 'Green' } else { 'Yellow' }
    $ethernetColor = if ($Observation.EthernetStatus -eq 'Up') { 'Green' } else { 'Yellow' }

    Write-Host "[$($Observation.Timestamp)] Radio $($Observation.RadioIp): ping=$($Observation.RadioPing) ARP=$($Observation.ArpMac)" -ForegroundColor $radioColor
    Write-Host "  Ethernet: $($Observation.EthernetAdapter) $($Observation.EthernetStatus) $($Observation.EthernetIPv4) $($Observation.EthernetLinkSpeed)" -ForegroundColor $ethernetColor
    Write-Host "  CHUD:     reachable=$($Observation.ChudReachable) devices=$($Observation.ChudDeviceCount) (configuration path)"
    Write-Host "  ARC:      reachable=$($Observation.ArcReachable) observed=$($Observation.ArcObservedNodes) connected=$($Observation.ArcConnectedNodes) links=$($Observation.ArcMeshLinks)"
}

Write-Section 'AVIAN real-radio connection monitor'
Write-Host 'This script is looking for four connection milestones:'
Write-Host '  1. The Ethernet carrier comes up when the powered radio is plugged in.'
Write-Host '  2. The radio appears at its management IP and MAC address in the neighbor table.'
Write-Host '  3. AVIAN publishes the real TrellisWare discovery to ARC.'
Write-Host '  4. ARC shows the real node and later its live connection/link state.'
Write-Host 'CHUD discovery is recorded separately because CHUD owns configuration, but it does not gate ARC discovery.'
Write-Host 'Wi-Fi and internet availability are not test requirements. All monitoring is local.' -ForegroundColor Green

Write-Section 'Select the interfaces'
Get-PhysicalAdapters | Format-Table Name, Status, LinkSpeed, InterfaceDescription -AutoSize
$EthernetAdapter = Select-AdapterName -RequestedName $EthernetAdapter -Kind Ethernet
if (-not $WifiAdapter) {
    $WifiAdapter = Get-PhysicalAdapters | Where-Object {
        $_.Name -match 'Wi-?Fi|Wireless|WLAN' -or $_.InterfaceDescription -match 'Wi-?Fi|Wireless|802\.11'
    } | Select-Object -First 1 -ExpandProperty Name
}

if (-not $RadioIp -or $RadioIp.Count -eq 0) {
    $inputIps = Read-Host 'Radio management IP address(es), comma-separated [10.1.0.2]'
    if ([string]::IsNullOrWhiteSpace($inputIps)) { $inputIps = '10.1.0.2' }
    $RadioIp = @($inputIps -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ })
}

foreach ($address in $RadioIp) {
    try {
        $parsed = [System.Net.IPAddress]::Parse($address)
        if ($parsed.AddressFamily -ne [System.Net.Sockets.AddressFamily]::InterNetwork) {
            throw 'Only IPv4 addresses are supported.'
        }
    } catch {
        throw "Invalid radio IPv4 address '$address'."
    }
}

$runId = Get-Date -Format 'yyyyMMdd-HHmmss'
$resultDirectory = Join-Path $ResultsRoot $runId
New-Item -ItemType Directory -Force -Path $resultDirectory | Out-Null
$csvPath = Join-Path $resultDirectory 'radio-connection-timeline.csv'
$summaryPath = Join-Path $resultDirectory 'summary.txt'
$networkBeforePath = Join-Path $resultDirectory 'network-before.txt'
$networkAfterPath = Join-Path $resultDirectory 'network-after.txt'

Write-Section 'Capture unplugged baseline'
Write-Host 'The baseline records ARC/CHUD and the radio interface before Ethernet changes.'
$baselineAnswer = Read-Host 'Leave the radio Ethernet cable unplugged, then press Enter. Type SKIP if it is already connected'
Get-NetAdapter | Format-Table Name, Status, LinkSpeed, InterfaceDescription -AutoSize | Out-String | Set-Content -LiteralPath $networkBeforePath
Get-NetIPConfiguration | Format-List | Out-String | Add-Content -LiteralPath $networkBeforePath
Get-NetRoute -AddressFamily IPv4 | Sort-Object DestinationPrefix, RouteMetric | Format-Table -AutoSize | Out-String | Add-Content -LiteralPath $networkBeforePath

foreach ($address in $RadioIp) {
    $baseline = Get-Observation -Address $address -EthernetName $EthernetAdapter -WifiName $WifiAdapter
    $baseline | Export-Csv -LiteralPath $csvPath -NoTypeInformation -Append
    Write-Observation -Observation $baseline
}

Write-Section 'Begin cable acquisition test'
Write-Host 'Power the radio on, connect its Ethernet cable, and then press Enter immediately.' -ForegroundColor Yellow
Write-Host 'The monitor will watch for link, IP reachability, CHUD discovery, and ARC ingestion.'
Read-Host 'Press Enter when the cable is connected' | Out-Null
Write-Host 'Monitoring. Press Q to stop and write the final report (Ctrl+C also stops).' -ForegroundColor Green

$firstEthernet = $null
$firstPing = @{}
$firstChud = $null
$firstArc = $null
$lastSignature = @{}
$lastHeartbeat = Get-Date

try {
    while ($true) {
        foreach ($address in $RadioIp) {
            $observation = Get-Observation -Address $address -EthernetName $EthernetAdapter -WifiName $WifiAdapter
            $observation | Export-Csv -LiteralPath $csvPath -NoTypeInformation -Append

            if (-not $firstEthernet -and $observation.EthernetStatus -eq 'Up') { $firstEthernet = $observation.Timestamp }
            if (-not $firstPing.ContainsKey($address) -and $observation.RadioPing) { $firstPing[$address] = $observation.Timestamp }
            if (-not $firstChud -and $observation.ChudDeviceCount -gt 0) { $firstChud = $observation.Timestamp }
            if (-not $firstArc -and $observation.ArcObservedNodes -gt 0) { $firstArc = $observation.Timestamp }

            $signature = @(
                $observation.RadioPing,
                $observation.ArpMac,
                $observation.EthernetStatus,
                $observation.EthernetIPv4,
                $observation.WifiStatus,
                $observation.DefaultRouteInterface,
                $observation.ChudReachable,
                $observation.ChudDeviceCount,
                $observation.ArcReachable,
                $observation.ArcObservedNodes,
                $observation.ArcConnectedNodes,
                $observation.ArcMeshLinks
            ) -join '|'
            if (-not $lastSignature.ContainsKey($address) -or $lastSignature[$address] -ne $signature -or ((Get-Date) - $lastHeartbeat).TotalSeconds -ge 30) {
                Write-Observation -Observation $observation
                $lastSignature[$address] = $signature
            }
        }

        if (((Get-Date) - $lastHeartbeat).TotalSeconds -ge 30) { $lastHeartbeat = Get-Date }
        if ([Console]::KeyAvailable) {
            $key = [Console]::ReadKey($true)
            if ($key.Key -eq [ConsoleKey]::Q) { break }
        }
        Start-Sleep -Seconds $IntervalSeconds
    }
} finally {
    Get-NetAdapter | Format-Table Name, Status, LinkSpeed, InterfaceDescription -AutoSize | Out-String | Set-Content -LiteralPath $networkAfterPath
    Get-NetIPConfiguration | Format-List | Out-String | Add-Content -LiteralPath $networkAfterPath
    Get-NetRoute -AddressFamily IPv4 | Sort-Object DestinationPrefix, RouteMetric | Format-Table -AutoSize | Out-String | Add-Content -LiteralPath $networkAfterPath

    $summary = @(
        "AVIAN real-radio connection test: $runId",
        "Ethernet adapter: $EthernetAdapter",
        "Wi-Fi adapter: $WifiAdapter",
        "Radio IPs: $($RadioIp -join ', ')",
        "First Ethernet link: $(if ($firstEthernet) { $firstEthernet } else { 'not observed' })",
        "First CHUD device: $(if ($firstChud) { $firstChud } else { 'not observed' })",
        "First ARC observation: $(if ($firstArc) { $firstArc } else { 'not observed' })"
    )
    foreach ($address in $RadioIp) {
        $pingTime = if ($firstPing.ContainsKey($address)) { $firstPing[$address] } else { 'not observed' }
        $summary += "First ping from $address`: $pingTime"
    }
    $summary | Set-Content -LiteralPath $summaryPath

    Write-Section 'Test stopped'
    $summary | ForEach-Object { Write-Host $_ }
    Write-Host "Results saved to: $resultDirectory" -ForegroundColor Green
}
