[package]
name = "mesh-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
mesh-core = { path = "../../crates/mesh-core" }
mesh-peat = { path = "../../crates/mesh-peat" }
tokio.workspace = true
vehicle-adapters = { path = "../../crates/vehicle-adapters" }

[features]
direct-serial = ["vehicle-adapters/direct-serial"]

[lints]
workspace = true
